# This is code that needs to be excuted if a user uploads a new passenger detail from the front-end

In [1]:
# First loading the models

In [2]:
import pickle
import numpy as np
import warnings
warnings.filterwarnings("ignore")

ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [3]:
# Assume this is the input
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [4]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [5]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1)) # applying ohe to the test data

In [6]:
test_input_sex

array([[0., 1.]])

In [7]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1)) # applying ohe to the test data

In [8]:
test_input_embarked 

array([[0., 0., 1.]])

In [9]:
test_input_age = test_input[:,2].reshape(1,1)

In [11]:
# Combining the above columns 
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [12]:
test_input_transformed.shape

(1, 10)

In [14]:
# Now I got the  preprocessed user input data which can be fit to my classifier
clf.predict(test_input_transformed)

array([1], dtype=int64)

This is the production code that needs to be written for deploying the code. As you can see, the same block of code is repeated for each user input value, and it's important to ensure the correct order of input values. THis process is time-consuming and there is a high probability of errors in the code, especially 
with regards to the order of inputted values.

### The series of code you write while training has to be written again while taking the code for produciton, which really is a bad thing because if somehing is changed on the training set the production set also has to be potimized

This is why pipelines are utilized, as they offer a more efficient and error-free approach to handle the multiple stages involved in data preprocessing, model training, and prediction. With pipelines, it is possible to automate and streamline the entire process, reducing the likelihood of errors and ensuring a more efficient deployment of machine learning models.